import type { LeadStatus, ProjectType } from '../types'

export const label = (value:string) => value.toLowerCase().replaceAll('_',' ').replace(/\b\w/g, c => c.toUpperCase())
export const LEAD_STATUSES:LeadStatus[] = ['NEW','INFO_NEEDED','DESIGN_DISCUSSION','READY_TO_PRICE','WAITING_FOR_ARTAN','READY_TO_QUOTE','QUOTE_IN_PREPARATION','QUOTE_SENT','WAITING_FOR_CLIENT','MATERIAL_SELECTION','SAMPLES_TO_SEND','SAMPLES_SENT','WAITING_FOR_SAMPLE_FEEDBACK','SITE_VISIT_NEEDED','SITE_VISIT_PROPOSED','SITE_VISIT_BOOKED','TEMPLATE_REQUIRED','WAITING_FOR_DEPOSIT','APPROVED','WON','LOST','DORMANT']
export const PROJECT_TYPES:ProjectType[] = ['BESPOKE_PORCELAIN_SINK','VANITY_AND_SINK','VANITY_TOP','WET_ROOM','LARGE_FORMAT_TILING','FEATURE_WALL','PORCELAIN_STAIRS','OTHER_BESPOKE_FABRICATION','OTHER']
export const JOB_STATUSES = ['CONFIRMED','DEPOSIT_PENDING','DEPOSIT_RECEIVED','MATERIAL_PENDING','MATERIAL_CONFIRMED','TEMPLATE_REQUIRED','TEMPLATE_BOOKED','TEMPLATE_COMPLETE','READY_FOR_FABRICATION','IN_FABRICATION','FABRICATION_COMPLETE','QUALITY_CHECK','READY_FOR_DELIVERY','DELIVERY_BOOKED','DELIVERED','INSTALLATION_BOOKED','INSTALLED','COMPLETED','ON_HOLD','CANCELLED'] as const
export const QUOTE_STATUSES = ['DRAFT','READY_FOR_REVIEW','ARTAN_REVIEW_NEEDED','APPROVED_INTERNALLY','SENT','REVISED','ACCEPTED','DECLINED','SUPERSEDED'] as const
export const WAITING_FOR = ['NOTHING','CLIENT','IOANNIS','ARTAN','SUPPLIER','INSTALLATION_TEAM','OTHER'] as const
export const QUOTE_CATEGORIES = ['FABRICATION','PORCELAIN_MATERIAL','VANITY','DRAWERS','PORCELAIN_CLADDING','SPLASHBACK_UPSTAND','ADDITIONAL_TAP_HOLES','OVERFLOW','REINFORCEMENT','TEMPLATE_VISIT','DELIVERY','INSTALLATION','OTHER'] as const
export const EVENT_TYPES = ['SITE_VISIT','TEMPLATE_VISIT','CLIENT_MEETING','FABRICATION_DEADLINE','DELIVERY','INSTALLATION','PAYMENT_DUE','OTHER'] as const
export const PAYMENT_TYPES = ['DEPOSIT','STAGE_PAYMENT','MATERIAL','DELIVERY','INSTALLATION','FINAL_PAYMENT','OTHER'] as const
export const DOCUMENT_CATEGORIES = ['QUOTATION','INVOICE','TECHNICAL_DRAWING','TEMPLATE','CLIENT_REFERENCE','MATERIAL_SPECIFICATION','SITE_PHOTO','FABRICATION_PHOTO','DELIVERY_DOCUMENT','OTHER'] as const
export const ACTIVE_LEAD_STATUSES = LEAD_STATUSES.filter(s => !['WON','LOST','DORMANT'].includes(s))
export const ACTIVE_JOB_STATUSES = JOB_STATUSES.filter(s => !['COMPLETED','CANCELLED'].includes(s))
