import { useState, type FormEvent } from 'react'
import { ArrowLeft, CalendarPlus, Check, Plus } from '@phosphor-icons/react'
import { useStore } from '../data/store'
import { JOB_STATUSES, PAYMENT_TYPES, WAITING_FOR, label } from '../lib/constants'
import { date, isoNow, money, uid } from '../lib/format'
import type { Note, Payment, Task } from '../types'
import { Button, DateDisplay, EmptyState, Field, FormActions, HealthBadge, KeyValue, Modal, Money, PageHeader, Panel, StatusBadge, Tabs } from '../components/ui'
import { NotFound } from './LeadDetail'

const tabs=['Overview','Specification','Quotes','Tasks','Calendar','Payments','Documents','Notes','Activity']
export function JobDetail({id}:{id:string}){const {db,update,add,log}=useStore();const job=db.jobs.find(j=>j.id===id);const [tab,setTab]=useState('Overview');const [addMode,setAddMode]=useState<'task'|'payment'|'note'|null>(null);if(!job)return <NotFound type="job"/>;const client=db.clients.find(c=>c.id===job.client_id)!;const lead=db.leads.find(l=>l.id===job.lead_id);const spec=db.specifications.find(s=>s.lead_id===job.lead_id);const quotes=db.quotes.filter(q=>q.lead_id===job.lead_id);const tasks=db.tasks.filter(t=>t.job_id===id);const payments=db.payments.filter(p=>p.job_id===id);const docs=db.documents.filter(d=>d.job_id===id||d.lead_id===job.lead_id);const notes=db.notes.filter(n=>n.job_id===id);const events=db.events.filter(e=>e.job_id===id);const activity=db.activities.filter(a=>a.job_id===id||a.lead_id===job.lead_id).sort((a,b)=>b.created_at.localeCompare(a.created_at));const paid=payments.filter(p=>p.status==='PAID').reduce((s,p)=>s+p.amount,0);const outstanding=Math.max(0,job.project_value-paid)
 const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const now=isoNow();if(addMode==='task'){const t:Task={id:uid('task'),lead_id:null,quote_id:null,job_id:id,title:String(d.get('title')),description:String(d.get('description')),owner:String(d.get('owner')),priority:String(d.get('priority')) as Task['priority'],status:'TODO',due_at:String(d.get('due_at'))||null,completed_at:null,created_at:now,updated_at:now};add('tasks',t)}if(addMode==='payment'){const status=String(d.get('status')) as Payment['status'];const p:Payment={id:uid('payment'),job_id:id,payment_type:String(d.get('payment_type')),amount:Number(d.get('amount')),due_date:String(d.get('due_date'))||null,paid_date:status==='PAID'?String(d.get('paid_date'))||now.slice(0,10):null,status,reference:String(d.get('reference')),invoice_document_id:null,notes:String(d.get('notes')),created_at:now,updated_at:now};add('payments',p);log({client_id:job.client_id,lead_id:job.lead_id,quote_id:null,job_id:id,action:'PAYMENT_RECORDED',description:`${label(p.payment_type)} payment recorded`,old_value_json:null,new_value_json:{amount:p.amount,status:p.status}})}if(addMode==='note'){const n:Note={id:uid('note'),lead_id:null,job_id:id,category:String(d.get('category')),content:String(d.get('content')),is_pinned:false,created_by:'Ioannis',created_at:now,updated_at:now};add('notes',n)}setAddMode(null)}
 return <><a href="#/jobs" className="back-link"><ArrowLeft/>Back to jobs</a><PageHeader eyebrow={`${client.name} · ${job.postcode}`} title={job.project_title} description={`Job linked to ${lead?.project_title||'original lead'}`} actions={<a className="button secondary" href={`#/leads/${job.lead_id}`}>Open original lead</a>}/><div className="record-status-line"><StatusBadge value={job.status}/><HealthBadge value={job.health}/></div><section className="job-financial-strip"><div><span>Project value</span><strong><Money value={job.project_value}/></strong></div><div><span>Paid</span><strong><Money value={paid}/></strong></div><div className={outstanding>0?'attention':''}><span>Outstanding</span><strong><Money value={outstanding}/></strong></div><div><span>Target completion</span><strong><DateDisplay value={job.target_completion_date}/></strong></div></section><section className="operational-strip compact"><div className="op-card warm"><span>Waiting for</span><strong>{label(job.waiting_for)}</strong><small>{job.health_reason||'No further detail'}</small></div><div className="op-card"><span>Next action</span><strong>{job.next_action||'Not set'}</strong><small>{job.next_action_owner}</small></div></section><div className="detail-actions"><Button variant="quiet" icon={<Plus/>} onClick={()=>setAddMode('task')}>Add task</Button><Button variant="quiet" icon={<CalendarPlus/>} onClick={()=>setTab('Calendar')}>Calendar</Button><Button variant="quiet" icon={<Plus/>} onClick={()=>setAddMode('payment')}>Record payment</Button><Button variant="quiet" icon={<Plus/>} onClick={()=>setAddMode('note')}>Add note</Button></div><Tabs items={tabs} active={tab} onChange={setTab}/><div className="detail-content">
 {tab==='Overview'&&<div className="two-column"><Panel title="Job controls"><div className="inline-edit"><Field label="Status"><select value={job.status} onChange={e=>{const old=job.status;update('jobs',id,{status:e.target.value as typeof job.status});log({client_id:job.client_id,lead_id:job.lead_id,quote_id:null,job_id:id,action:'JOB_STATUS_CHANGED',description:`Job status changed from ${label(old)} to ${label(e.target.value)}`,old_value_json:{status:old},new_value_json:{status:e.target.value}})}}>{JOB_STATUSES.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Health"><select value={job.health} onChange={e=>update('jobs',id,{health:e.target.value as typeof job.health})}><option>GREEN</option><option>AMBER</option><option>RED</option></select></Field><Field label="Waiting for"><select value={job.waiting_for} onChange={e=>update('jobs',id,{waiting_for:e.target.value as typeof job.waiting_for})}>{WAITING_FOR.map(v=><option key={v}>{v}</option>)}</select></Field></div></Panel><Panel title="Project details"><div className="key-grid"><KeyValue label="Project type">{label(job.project_type)}</KeyValue><KeyValue label="Address">{job.project_address}</KeyValue><KeyValue label="Start date"><DateDisplay value={job.start_date}/></KeyValue><KeyValue label="Target"><DateDisplay value={job.target_completion_date}/></KeyValue><KeyValue label="Accepted quote">{quotes.find(q=>q.id===job.accepted_quote_id)?.quote_number}</KeyValue><KeyValue label="Lead"><a href={`#/leads/${job.lead_id}`}>{lead?.project_title}</a></KeyValue></div></Panel></div>}
 {tab==='Specification'&&<Panel title="Linked specification">{spec?<div className="key-grid"><KeyValue label="Overall dimensions">{spec.width_mm&&spec.depth_mm?`${spec.width_mm} × ${spec.depth_mm} mm`:'—'}</KeyValue><KeyValue label="Mounting">{label(spec.mounting_type)}</KeyValue><KeyValue label="Drain">{label(spec.drain_type)}</KeyValue><KeyValue label="Finish">{spec.finish}</KeyValue><KeyValue label="Technical notes">{spec.technical_notes}</KeyValue></div>:<EmptyState title="No linked specification" description="Add it on the original lead."/>}</Panel>}
 {tab==='Quotes'&&<Panel title="Linked quotations">{quotes.map(q=><div className="record-line" key={q.id}><div><strong>{q.quote_number} v{q.version}</strong><span>{date(q.quote_date)}</span></div><StatusBadge value={q.status}/><Money value={q.total}/></div>)}</Panel>}
 {tab==='Tasks'&&<Panel title="Job tasks" action={<Button onClick={()=>setAddMode('task')}>Add task</Button>}>{tasks.length?<div className="simple-list">{tasks.map(t=><article key={t.id}><button className={`task-check ${t.status==='DONE'?'done':''}`} onClick={()=>update('tasks',t.id,{status:t.status==='DONE'?'TODO':'DONE',completed_at:t.status==='DONE'?null:isoNow()})}><Check/></button><div><strong>{t.title}</strong><span>{t.owner} · {date(t.due_at)}</span></div><StatusBadge value={t.status}/></article>)}</div>:<EmptyState title="No job tasks" description="Add a delivery, fabrication or admin task."/>}</Panel>}
 {tab==='Calendar'&&<Panel title="Job calendar">{events.length?<div className="simple-list">{events.map(e=><article key={e.id}><span className="date-block"><b>{date(e.start_at,{day:'2-digit'})}</b>{date(e.start_at,{month:'short'})}</span><div><strong>{e.title}</strong><span>{e.location}</span></div><StatusBadge value={e.status}/></article>)}</div>:<EmptyState title="No job events" description="Create events from the Calendar page."/>}</Panel>}
 {tab==='Payments'&&<Panel title="Payment schedule" subtitle={`${money(paid)} paid · ${money(outstanding)} outstanding`} action={<Button onClick={()=>setAddMode('payment')}>Record payment</Button>}>{payments.length?<div className="simple-list payments-list">{payments.map(p=><article key={p.id}><div><strong>{label(p.payment_type)}</strong><span>Due {date(p.due_date)}{p.reference?` · ${p.reference}`:''}</span></div><Money value={p.amount}/><StatusBadge value={p.status}/></article>)}</div>:<EmptyState title="No payments recorded" description="Record expected and completed payments explicitly."/>}</Panel>}
 {tab==='Documents'&&<Panel title="Linked documents">{docs.length?docs.map(d=><div className="record-line" key={d.id}><div><strong>{d.title}</strong><span>{d.file_name}</span></div><StatusBadge value={d.category}/></div>):<EmptyState title="No linked documents" description="Documents from the lead and job appear here."/>}</Panel>}
 {tab==='Notes'&&<Panel title="Job notes" action={<Button onClick={()=>setAddMode('note')}>Add note</Button>}>{notes.length?<div className="note-grid">{notes.map(n=><article key={n.id}><small>{label(n.category)}</small><p>{n.content}</p><span>{date(n.created_at)}</span></article>)}</div>:<EmptyState title="No job notes" description="Add fabrication or site context here."/>}</Panel>}
 {tab==='Activity'&&<Panel title="Project activity"><div className="activity-list">{activity.map(a=><div key={a.id}><i/><div><strong>{a.description}</strong><span>{a.created_by} · {date(a.created_at)}</span></div></div>)}</div></Panel>}
 </div>{addMode&&<Modal title={addMode==='payment'?'Record payment':`Add ${addMode}`} onClose={()=>setAddMode(null)}><form onSubmit={save} className="form-grid">{addMode==='task'&&<><Field label="Title" className="span-2"><input name="title" required/></Field><Field label="Owner"><input name="owner" defaultValue="Ioannis"/></Field><Field label="Priority"><select name="priority"><option>NORMAL</option><option>HIGH</option><option>LOW</option></select></Field><Field label="Due"><input name="due_at" type="date"/></Field><Field label="Description" className="span-2"><textarea name="description"/></Field></>}{addMode==='payment'&&<><Field label="Type"><select name="payment_type">{PAYMENT_TYPES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Amount"><input name="amount" type="number" min="0" step="0.01" required/></Field><Field label="Due date"><input name="due_date" type="date"/></Field><Field label="Status"><select name="status"><option>UPCOMING</option><option>DUE</option><option>OVERDUE</option><option>PAID</option><option>CANCELLED</option></select></Field><Field label="Paid date"><input name="paid_date" type="date"/></Field><Field label="Reference"><input name="reference"/></Field><Field label="Notes" className="span-2"><textarea name="notes"/></Field></>}{addMode==='note'&&<><Field label="Category"><select name="category"><option>GENERAL</option><option>TECHNICAL</option><option>SITE</option><option>FABRICATION</option><option>INTERNAL</option></select></Field><Field label="Note" className="span-2"><textarea name="content" rows={4} required/></Field></>}<div className="span-2"><FormActions onCancel={()=>setAddMode(null)} submit="Save"/></div></form></Modal>}</>}
