import { useEffect, useState, type FormEvent } from 'react'
import { ArrowRight, Plus, UserPlus } from '@phosphor-icons/react'
import { useStore } from '../data/store'
import { ACTIVE_LEAD_STATUSES, LEAD_STATUSES, PROJECT_TYPES, WAITING_FOR, label } from '../lib/constants'
import { isoNow, uid, date } from '../lib/format'
import type { Client, Lead, LeadStatus, Priority, ProjectType, WaitingFor } from '../types'
import { Button, EmptyState, Field, FormActions, Modal, PageHeader, PriorityBadge, Select, StatusBadge, Toolbar } from '../components/ui'

export function Leads({query}:{query:URLSearchParams}){
 const {db,add,log}=useStore(); const [search,setSearch]=useState(''); const [filter,setFilter]=useState(query.get('filter')||'ACTIVE'); const [create,setCreate]=useState(query.get('new')==='1'); const [clientModal,setClientModal]=useState(false)
 useEffect(()=>{if(query.get('new')==='1')setCreate(true)},[query])
 const rows=db.leads.filter(l=>{
  const c=db.clients.find(x=>x.id===l.client_id); const q=`${c?.name} ${c?.company} ${l.project_title} ${l.postcode}`.toLowerCase();
  const matches=filter==='ALL'||(filter==='ACTIVE'&&ACTIVE_LEAD_STATUSES.includes(l.status))||(filter==='attention'&&(l.priority==='HIGH'||!!(l.next_action_due&&l.next_action_due<new Date().toISOString().slice(0,10))))||l.status===filter
  return matches&&q.includes(search.toLowerCase())
 })
 const saveLead=(data:Omit<Lead,'id'|'created_at'|'updated_at'|'won_at'|'lost_at'|'lost_reason'|'last_client_contact_at'|'last_artiling_contact_at'>)=>{const lead:Lead={...data,id:uid('lead'),created_at:isoNow(),updated_at:isoNow(),won_at:null,lost_at:null,lost_reason:'',last_client_contact_at:null,last_artiling_contact_at:null};add('leads',lead);log({client_id:lead.client_id,lead_id:lead.id,quote_id:null,job_id:null,action:'LEAD_CREATED',description:'Lead created',old_value_json:null,new_value_json:{status:lead.status}});setCreate(false);location.hash=`/leads/${lead.id}`}
 const saveClient=(client:Client)=>{add('clients',client);setClientModal(false)}
 return <>
  <PageHeader eyebrow="Commercial pipeline" title="Leads" description={`${db.leads.filter(l=>ACTIVE_LEAD_STATUSES.includes(l.status)).length} active enquiries across the studio.`} actions={<><Button variant="secondary" icon={<UserPlus/>} onClick={()=>setClientModal(true)}>New client</Button><Button icon={<Plus/>} onClick={()=>setCreate(true)}>New lead</Button></>}/>
  <Toolbar search={search} onSearch={setSearch}><Select value={filter} onChange={setFilter} label="Lead status"><option value="ACTIVE">Active</option><option value="attention">Needs attention</option><option value="ALL">All leads</option>{['NEW','INFO_NEEDED','WAITING_FOR_ARTAN','READY_TO_QUOTE','QUOTE_SENT','WAITING_FOR_CLIENT','WON','LOST','DORMANT'].map(s=><option value={s} key={s}>{label(s)}</option>)}</Select><span className="result-count">{rows.length} records</span></Toolbar>
  {rows.length?<div className="responsive-data lead-data"><div className="data-head"><span>Client / project</span><span>Location</span><span>Status</span><span>Waiting for</span><span>Next action</span><span>Priority</span><span/></div>{rows.map(l=>{const c=db.clients.find(x=>x.id===l.client_id);const quote=db.quotes.filter(q=>q.lead_id===l.id).sort((a,b)=>b.version-a.version)[0];return <a href={`#/leads/${l.id}`} className="data-row" key={l.id}><div className="primary-cell"><strong>{c?.name}</strong><span>{l.project_title}</span>{c?.company&&<small>{c.company}</small>}</div><div data-label="Location"><span>{l.postcode||'—'}</span></div><div data-label="Status"><StatusBadge value={l.status}/>{quote&&<small>{quote.quote_number} v{quote.version}</small>}</div><div data-label="Waiting for"><span>{label(l.waiting_for)}</span><small>{l.waiting_for_detail}</small></div><div data-label="Next action"><span>{l.next_action||'—'}</span><small>{l.next_action_due?date(l.next_action_due):''}</small></div><div data-label="Priority"><PriorityBadge value={l.priority}/>{l.artans_review_required&&<small className="review-flag">Artan review</small>}</div><ArrowRight className="row-arrow"/></a>})}</div>:<EmptyState title="No leads match this view" description="Change the filter or add a new enquiry." action={<Button icon={<Plus/>} onClick={()=>setCreate(true)}>Create lead</Button>}/>} 
  {create&&<LeadForm clients={db.clients} onClose={()=>setCreate(false)} onSave={saveLead}/>} {clientModal&&<ClientForm onClose={()=>setClientModal(false)} onSave={saveClient}/>} 
 </>
}

function LeadForm({clients,onClose,onSave}:{clients:Client[];onClose:()=>void;onSave:(lead:Omit<Lead,'id'|'created_at'|'updated_at'|'won_at'|'lost_at'|'lost_reason'|'last_client_contact_at'|'last_artiling_contact_at'>)=>void}){
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);onSave({client_id:String(d.get('client_id')),project_title:String(d.get('project_title')),project_type:String(d.get('project_type')) as ProjectType,description:String(d.get('description')),lead_source:String(d.get('lead_source')),status:String(d.get('status')) as LeadStatus,priority:String(d.get('priority')) as Priority,project_address:String(d.get('project_address')),postcode:String(d.get('postcode')),waiting_for:String(d.get('waiting_for')) as WaitingFor,waiting_for_detail:String(d.get('waiting_for_detail')),next_action:String(d.get('next_action')),next_action_owner:String(d.get('next_action_owner')),next_action_due:String(d.get('next_action_due'))||null,artans_review_required:d.get('artans_review_required')==='on'})}
 return <Modal title="Create lead" description="Capture the commercial essentials now; technical detail can follow." onClose={onClose} wide><form onSubmit={submit} className="form-grid"><Field label="Client"><select name="client_id" required defaultValue=""><option value="" disabled>Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}{c.company?` — ${c.company}`:''}</option>)}</select></Field><Field label="Project title"><input name="project_title" required placeholder="e.g. Hampstead guest bathroom"/></Field><Field label="Project type"><select name="project_type" defaultValue="BESPOKE_PORCELAIN_SINK">{PROJECT_TYPES.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></Field><Field label="Lead source"><input name="lead_source" placeholder="Website, referral, Instagram…"/></Field><Field label="Status"><select name="status" defaultValue="NEW">{LEAD_STATUSES.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></Field><Field label="Priority"><select name="priority" defaultValue="NORMAL"><option>HIGH</option><option>NORMAL</option><option>LOW</option></select></Field><Field label="Project address" className="span-2"><input name="project_address"/></Field><Field label="Postcode"><input name="postcode"/></Field><Field label="Waiting for"><select name="waiting_for" defaultValue="NOTHING">{WAITING_FOR.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></Field><Field label="Waiting for detail" className="span-2"><input name="waiting_for_detail" placeholder="What is holding progress?"/></Field><Field label="Next action" className="span-2"><input name="next_action" placeholder="What should happen next?"/></Field><Field label="Owner"><input name="next_action_owner" defaultValue="Ioannis"/></Field><Field label="Due date"><input name="next_action_due" type="date"/></Field><Field label="Description" className="span-2"><textarea name="description" rows={3}/></Field><label className="check-field span-2"><input type="checkbox" name="artans_review_required"/><span>Artan review required</span></label><div className="span-2"><FormActions onCancel={onClose} submit="Create lead"/></div></form></Modal>
}

function ClientForm({onClose,onSave}:{onClose:()=>void;onSave:(client:Client)=>void}){
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const now=isoNow();onSave({id:uid('client'),name:String(d.get('name')),company:String(d.get('company')),email:String(d.get('email')),phone:String(d.get('phone')),preferred_contact:String(d.get('preferred_contact')),billing_address:String(d.get('billing_address')),notes:String(d.get('notes')),created_at:now,updated_at:now})}
 return <Modal title="Create client" description="Clients are shared across every enquiry and project." onClose={onClose}><form onSubmit={submit} className="form-grid"><Field label="Name" className="span-2"><input name="name" required autoFocus/></Field><Field label="Company"><input name="company"/></Field><Field label="Preferred contact"><select name="preferred_contact"><option>Email</option><option>Phone</option><option>WhatsApp</option></select></Field><Field label="Email"><input name="email" type="email"/></Field><Field label="Phone"><input name="phone" type="tel"/></Field><Field label="Billing address" className="span-2"><textarea name="billing_address" rows={2}/></Field><Field label="Notes" className="span-2"><textarea name="notes" rows={2}/></Field><div className="span-2"><FormActions onCancel={onClose} submit="Create client"/></div></form></Modal>
}
