import { useState } from 'react'
import { ArrowRight, DownloadSimple, FilePdf } from '@phosphor-icons/react'
import { useStore } from '../data/store'
import { QUOTE_STATUSES, label } from '../lib/constants'
import { date, money } from '../lib/format'
import { EmptyState, Money, PageHeader, Select, StatusBadge, Toolbar } from '../components/ui'

export function QuotesPage({query}:{query:URLSearchParams}){
 const {db}=useStore();const [search,setSearch]=useState('');const [filter,setFilter]=useState(query.get('filter')||'ALL')
 const rows=db.quotes.filter(q=>{const lead=db.leads.find(l=>l.id===q.lead_id);const client=db.clients.find(c=>c.id===lead?.client_id);return (filter==='ALL'||q.status===filter)&&`${q.quote_number} ${lead?.project_title} ${client?.name}`.toLowerCase().includes(search.toLowerCase())}).sort((a,b)=>b.updated_at.localeCompare(a.updated_at))
 const current=db.quotes.filter(q=>q.status!=='SUPERSEDED');const sent=current.filter(q=>q.status==='SENT');const accepted=current.filter(q=>q.status==='ACCEPTED');const today=new Date().toISOString().slice(0,10);const expiring=sent.filter(q=>q.valid_until&&q.valid_until<today)
 return <><PageHeader eyebrow="Commercial" title="Quotations" description="Track every issued price, the PDF sent to the client and what converts into confirmed work."/>
  <section className="quote-summary"><div><span>Live quotations</span><strong>{current.length}</strong><small>Current versions</small></div><div><span>Sent value</span><strong>{money(sent.reduce((sum,q)=>sum+q.total,0))}</strong><small>{sent.length} awaiting decisions</small></div><div><span>Accepted value</span><strong>{money(accepted.reduce((sum,q)=>sum+q.total,0))}</strong><small>{accepted.length} converted</small></div><div className={expiring.length?'attention':''}><span>Expired validity</span><strong>{expiring.length}</strong><small>Review before following up</small></div></section>
  <Toolbar search={search} onSearch={setSearch}><Select value={filter} onChange={setFilter}><option value="ALL">All statuses</option>{QUOTE_STATUSES.map(s=><option value={s} key={s}>{label(s)}</option>)}</Select><span className="result-count">{rows.length} {rows.length===1?'record':'records'}</span></Toolbar>
  {rows.length?<div className="responsive-data quote-data quote-center"><div className="data-head"><span>Quote</span><span>Client / project</span><span>Date</span><span>Status</span><span>Total</span><span>Artan review</span><span>Updated</span><span>Actions</span></div>{rows.map(q=>{const lead=db.leads.find(l=>l.id===q.lead_id);const client=db.clients.find(c=>c.id===lead?.client_id);const document=db.documents.find(d=>d.quote_id===q.id);return <div className="data-row" key={q.id}><div className="primary-cell"><a className="quote-number-link" href={`#/leads/${q.lead_id}?tab=Quotes`}><strong>{q.quote_number}</strong><span>Version {q.version}</span></a></div><div data-label="Project"><strong>{client?.name}</strong><span>{lead?.project_title}</span></div><div data-label="Date">{date(q.quote_date)}</div><div data-label="Status"><StatusBadge value={q.status}/></div><div data-label="Total"><Money value={q.total}/></div><div data-label="Artan review"><StatusBadge value={q.artans_review_status}/></div><div data-label="Updated">{date(q.updated_at)}</div><div className="quote-row-actions" data-label="Actions">{document?.file_url&&<><a href={document.file_url} target="_blank" rel="noreferrer" aria-label={`View ${q.quote_number}`} title="View PDF"><FilePdf/></a><a href={`${document.file_url}?download=1`} download={document.file_name||true} aria-label={`Download ${q.quote_number}`} title="Download PDF"><DownloadSimple/></a></>}<a href={`#/leads/${q.lead_id}?tab=Quotes`} aria-label={`Open ${q.quote_number}`} title="Open quote"><ArrowRight/></a></div></div>})}</div>:<EmptyState title="No quotations match this view" description="Prepare quotations from a lead record."/>}
 </>
}
