export type Id = string
export type LeadStatus = 'NEW'|'INFO_NEEDED'|'DESIGN_DISCUSSION'|'READY_TO_PRICE'|'WAITING_FOR_ARTAN'|'READY_TO_QUOTE'|'QUOTE_IN_PREPARATION'|'QUOTE_SENT'|'WAITING_FOR_CLIENT'|'MATERIAL_SELECTION'|'SAMPLES_TO_SEND'|'SAMPLES_SENT'|'WAITING_FOR_SAMPLE_FEEDBACK'|'SITE_VISIT_NEEDED'|'SITE_VISIT_PROPOSED'|'SITE_VISIT_BOOKED'|'TEMPLATE_REQUIRED'|'WAITING_FOR_DEPOSIT'|'APPROVED'|'WON'|'LOST'|'DORMANT'
export type ProjectType = 'BESPOKE_PORCELAIN_SINK'|'VANITY_AND_SINK'|'VANITY_TOP'|'WET_ROOM'|'LARGE_FORMAT_TILING'|'FEATURE_WALL'|'PORCELAIN_STAIRS'|'OTHER_BESPOKE_FABRICATION'|'OTHER'
export type Priority = 'HIGH'|'NORMAL'|'LOW'
export type WaitingFor = 'CLIENT'|'IOANNIS'|'ARTAN'|'SUPPLIER'|'INSTALLATION_TEAM'|'OTHER'|'NOTHING'
export type QuoteStatus = 'DRAFT'|'READY_FOR_REVIEW'|'ARTAN_REVIEW_NEEDED'|'APPROVED_INTERNALLY'|'SENT'|'REVISED'|'ACCEPTED'|'DECLINED'|'SUPERSEDED'
export type ReviewStatus = 'NOT_REQUIRED'|'REQUESTED'|'APPROVED'|'CHANGES_REQUESTED'
export type JobStatus = 'CONFIRMED'|'DEPOSIT_PENDING'|'DEPOSIT_RECEIVED'|'MATERIAL_PENDING'|'MATERIAL_CONFIRMED'|'TEMPLATE_REQUIRED'|'TEMPLATE_BOOKED'|'TEMPLATE_COMPLETE'|'READY_FOR_FABRICATION'|'IN_FABRICATION'|'FABRICATION_COMPLETE'|'QUALITY_CHECK'|'READY_FOR_DELIVERY'|'DELIVERY_BOOKED'|'DELIVERED'|'INSTALLATION_BOOKED'|'INSTALLED'|'COMPLETED'|'ON_HOLD'|'CANCELLED'
export type Health = 'GREEN'|'AMBER'|'RED'
export type TaskStatus = 'TODO'|'IN_PROGRESS'|'WAITING'|'DONE'
export type PaymentStatus = 'DUE'|'UPCOMING'|'OVERDUE'|'PAID'|'CANCELLED'

export interface Client { id:Id; name:string; company:string; email:string; phone:string; preferred_contact:string; billing_address:string; notes:string; created_at:string; updated_at:string }
export interface Lead { id:Id; client_id:Id; project_title:string; project_type:ProjectType; description:string; lead_source:string; status:LeadStatus; priority:Priority; project_address:string; postcode:string; waiting_for:WaitingFor; waiting_for_detail:string; next_action:string; next_action_owner:string; next_action_due:string|null; last_client_contact_at:string|null; last_artiling_contact_at:string|null; artans_review_required:boolean; created_at:string; updated_at:string; won_at:string|null; lost_at:string|null; lost_reason:string; archived_at?:string|null; archived_reason?:string }
export interface LeadSpecification { id:Id; lead_id:Id; quantity:number|null; width_mm:number|null; depth_mm:number|null; height_mm:number|null; basin_width_mm:number|null; basin_depth_mm:number|null; mounting_type:string; slope_type:string; drain_type:string; tap_arrangement:string; tap_holes:number|null; vanity_required:boolean; drawer_configuration:string; cladding_required:boolean; splashback_required:boolean; overflow_required:boolean; reinforcement_required:boolean; material_supply_type:string; finish:string; special_requirements:string; technical_notes:string; updated_at:string }
export interface QuoteItem { id:Id; quote_id:Id; category:string; description:string; quantity:number; unit_price:number; total:number; is_optional:boolean; is_included:boolean; client_note:string; internal_note:string; sort_order:number }
export interface Quote { id:Id; lead_id:Id; job_id:Id|null; quote_number:string; version:number; status:QuoteStatus; quote_date:string; valid_until:string|null; subtotal:number; vat:number; total:number; artans_review_status:ReviewStatus; artans_reviewed_at:string|null; revision_reason:string; parent_quote_id:Id|null; client_notes:string; internal_notes:string; created_at:string; updated_at:string }
export interface Job { id:Id; lead_id:Id; client_id:Id; project_title:string; project_type:ProjectType; status:JobStatus; health:Health; health_reason:string; project_address:string; postcode:string; accepted_quote_id:Id|null; project_value:number; start_date:string|null; target_completion_date:string|null; actual_completion_date:string|null; waiting_for:WaitingFor; next_action:string; next_action_owner:string; created_at:string; updated_at:string; completed_at:string|null }
export interface Task { id:Id; lead_id:Id|null; quote_id:Id|null; job_id:Id|null; title:string; description:string; owner:string; priority:Priority; status:TaskStatus; due_at:string|null; completed_at:string|null; created_at:string; updated_at:string }
export interface EventRecord { id:Id; lead_id:Id|null; job_id:Id|null; event_type:string; title:string; start_at:string; end_at:string|null; location:string; assigned_to:string; status:string; notes:string; created_at:string; updated_at:string }
export interface Payment { id:Id; job_id:Id; payment_type:string; amount:number; due_date:string|null; paid_date:string|null; status:PaymentStatus; reference:string; invoice_document_id:Id|null; notes:string; created_at:string; updated_at:string }
export interface Material { id:Id; name:string; manufacturer:string; supplier:string; style_category:string; finish:string; colour:string; slab_width_mm:number|null; slab_height_mm:number|null; product_url:string; supplier_reference:string; cost:number|null; availability_status:string; availability_checked_at:string|null; sample_available:boolean; notes:string; created_at:string; updated_at:string }
export interface DocumentRecord { id:Id; client_id:Id|null; lead_id:Id|null; quote_id:Id|null; job_id:Id|null; material_id:Id|null; payment_id:Id|null; category:string; title:string; file_url:string; file_name:string; mime_type:string; notes:string; uploaded_at:string; uploaded_by:string }
export interface Note { id:Id; lead_id:Id|null; job_id:Id|null; category:string; content:string; is_pinned:boolean; created_by:string; created_at:string; updated_at:string }
export interface Activity { id:Id; client_id:Id|null; lead_id:Id|null; quote_id:Id|null; job_id:Id|null; action:string; description:string; old_value_json:unknown|null; new_value_json:unknown|null; created_by:string; created_at:string }
export interface Settings { company_name:string; email:string; phone:string; address:string; quote_valid_days:number; default_payment_terms:string }
export interface Database { clients:Client[]; leads:Lead[]; specifications:LeadSpecification[]; quotes:Quote[]; quoteItems:QuoteItem[]; jobs:Job[]; tasks:Task[]; events:EventRecord[]; payments:Payment[]; materials:Material[]; documents:DocumentRecord[]; notes:Note[]; activities:Activity[]; settings:Settings }
